name: feature

on:
    push:
        branches:
            - 'feature/**'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build